name: polyo-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - numba
  - matplotlib
  - seaborn
  - scikit-learn
  - cython
  - cryptography
  - streamlit
  - pip
  - cmake
  - ninja
  - make
  - pip:
      - gymnasium
      - tensorboard
      - pyro-ppl
      - stable-baselines3
      - "ray[rllib]"
      - requests
      - openai
      - telethon
      - tqdm
      - plotly
